# Generated by Django 2.2.5 on 2019-09-27 23:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_category_item_product_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=models.FilePathField(match='pencil', path='ecommerce/img/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='prodInferred',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.FinalCategory'),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent_cat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.Category')),
            ],
        ),
        migrations.AddField(
            model_name='finalcategory',
            name='parent_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.SubCategory'),
        ),
    ]
